apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hello-dev
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml

images:
  - name: quay.io/openshift/origin-hello-openshift
    newTag: main-ea23d22f-3b92-4e76-aa28-1c1416c61aef